# Generated by Django 2.2.6 on 2019-10-04 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_address', models.TextField(max_length=400, null=True)),
                ('end_address', models.TextField(max_length=400, null=True)),
                ('start_latlng', models.TextField(max_length=400, null=True)),
                ('end_latlng', models.TextField(max_length=400, null=True)),
                ('time_delivery', models.TimeField(null=True)),
                ('date_delivery', models.DateField(null=True)),
                ('is_adhoc', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=True)),
                ('payload', models.TextField(max_length=400, null=True)),
                ('delivery_type', models.TextField(max_length=400, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.TextField(max_length=400, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TripJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripjob_job', to='apiserver.Job')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripjob_trip', to='apiserver.Trip')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
