# Generated by Django 2.2.6 on 2019-10-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='valid',
            new_name='is_valid',
        ),
        migrations.RemoveField(
            model_name='job',
            name='end_latlng',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start_latlng',
        ),
        migrations.AddField(
            model_name='job',
            name='end_lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='end_lng',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='start_lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='start_lng',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
